version: '3.8'

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "4500:4500"
    restart: always

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always